---
pathOut: "/home/gchahine/optimizerOutput/"
graphConstraints: "/home/gchahine/packages/dream-multi-checker/build/2/19/graph_input.csv"
graphInitValues: "/home/gchahine/packages/dream-multi-checker/build/2/19/graph_initial_estimate.csv"
maxIterations: "1000"
autoMatchDir:
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/0/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/1/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/2/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/3/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/4/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/5/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/6/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/7/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/8/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/9/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/10/"
- "/mnt/storage/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/11/"
transformsCsv: "/home/gchahine/packages/dream-multi-checker/build/2/19/ol_transforms.csv"
autoNameTemplate: "semantic_icp_"
useDEM: "false"
DEM: "/home/gchahine/lake_modified.XYZ"
DEM_x0: "296725.10986414447"
DEM_y0: "5442395.173279924"

